/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Controller.BayarCicilanController;
import Controller.cicilanController;
import Model.Cicilan;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author LENOVO
 */
public class BayarCicilanForm extends javax.swing.JFrame {

    /**
     * Creates new form BayarCicilanForm
     */
    Cicilan cicilan;
    cicilanController cicilanController;
    
    public BayarCicilanForm() {
        initComponents();
        setLocationRelativeTo(null);
        cicilanController=new cicilanController(this);
        cicilanController.showDataCicilan();
    }
    
   public JButton getJButtonTambah()
   {
       return btntambah;
   }
   
   public JButton getJButtonHapus()
   {
      return btnhapus;
   }
   
   public JButton getJButtonCetak()
   {
      return btncetak;
   }
   
   public JLabel getJLabelNoKtp()
   {
       return lblnoktp;
   }
   
   public JLabel getJLabelNama()
   {
       return lblnama;
   }
   
   public JLabel getJLabelJenisKelamin()
   {
       return lbljeniskelamin;
   }
   
   public JLabel getJLabelAlamat()
   {
       return lblalamat;
   }
   
   public JLabel getJLabelNoTelp()
   {
       return lblnotelp;
   }
   
   public JLabel getJLabelCicilanKe()
   {
       return lblcicilanke;
   }
   
   public JLabel getJLabelKodeCicilan()
   {
       return lblkodecicilan;
   }
   
   public JLabel getJLabelKodeMotor()
   {
       return lblkodemotor;
   }
   public JLabel getJLabelNamaMotor()
   {
       return lblnamamotor;
   }
   public JLabel getJLabelMerk()
   {
       return lblmerkmotor;
   }
   public JLabel getJLabelWarna()
   {
       return lblwarnamotor;
   }
   
   public JLabel getJLabelKodePaket()
   {
       return lblkodepaket;
   }
   
   public JLabel getJLabelJmlCicilan()
   {
       return lbljmlcicilan;
   }
   
   public JLabel getJLabelNilaiCicilan()
   {
       return lblnilaicicilan;
   }
   
   public JLabel getJLabelBunga()
   {
       return lblbunga;
   }
   
   public JLabel getJLabelUangMuka()
   {
       return lbluangmuka;
   }
   
   public JLabel getJLabelHargaTotal()
   {
       return lblhargatotal;
   }
   
   public JTextField getJTextFieldCari()
   {
       return txtcaridata;
   }
   
   public JComboBox cbKategori()
   {
       return cbkategori;
   }
   
   
   public JComboBox cbBerdasarkan()
   {
       return cbberdasarkan;
   }
   
   public JRadioButton getRbDataBeli()
   {
       return  rbdatabeli;
   }
   
   public JRadioButton getRbDataCicilan()
   {
       return rbdatacicilan;
   }
   
   public JTable getTblCicilan()
   {
       return tblcicilan;
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcicilan = new rojerusan.RSTableMetro();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblnotelp = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblnoktp = new javax.swing.JLabel();
        lblnama = new javax.swing.JLabel();
        lbljeniskelamin = new javax.swing.JLabel();
        lblalamat = new javax.swing.JLabel();
        btncetak = new rojerusan.RSButtonMetro();
        btntambah = new rojerusan.RSButtonMetro();
        btnhapus = new rojerusan.RSButtonMetro();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblhargatotal = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblkodepaket = new javax.swing.JLabel();
        lblcicilanke = new javax.swing.JLabel();
        lblkodecicilan = new javax.swing.JLabel();
        lblkodemotor = new javax.swing.JLabel();
        lblnamamotor = new javax.swing.JLabel();
        lblmerkmotor = new javax.swing.JLabel();
        lblwarnamotor = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lbljmlcicilan = new javax.swing.JLabel();
        lblnilaicicilan = new javax.swing.JLabel();
        lblbunga = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbluangmuka = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        txtcaridata = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        cbberdasarkan = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        cbkategori = new javax.swing.JComboBox<>();
        rSButtonMetro1 = new rojerusan.RSButtonMetro();
        jPanel6 = new javax.swing.JPanel();
        rbdatabeli = new javax.swing.JRadioButton();
        rbdatacicilan = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 111, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Image/back.png"))); // NOI18N
        rSPanelImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSPanelImage1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 680));

        tblcicilan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblcicilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcicilanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcicilan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 1050, 220));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Biodata Pembeli:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(99, 111, 254))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(99, 111, 254));
        jLabel4.setText("Jenis Kelamin:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lblnotelp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblnotelp.setForeground(new java.awt.Color(99, 111, 254));
        lblnotelp.setText("...");
        jPanel3.add(lblnotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(99, 111, 254));
        jLabel6.setText("Nama:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(99, 111, 254));
        jLabel7.setText("Alamat:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(99, 111, 254));
        jLabel8.setText("No Telp:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 223, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(99, 111, 254));
        jLabel9.setText("No KTP:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblnoktp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblnoktp.setForeground(new java.awt.Color(99, 111, 254));
        lblnoktp.setText("...");
        jPanel3.add(lblnoktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        lblnama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblnama.setForeground(new java.awt.Color(99, 111, 254));
        lblnama.setText("...");
        jPanel3.add(lblnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 105, -1, -1));

        lbljeniskelamin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbljeniskelamin.setForeground(new java.awt.Color(99, 111, 254));
        lbljeniskelamin.setText("...");
        jPanel3.add(lbljeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        lblalamat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblalamat.setForeground(new java.awt.Color(99, 111, 254));
        lblalamat.setText("...");
        jPanel3.add(lblalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        btncetak.setText("Cetak");
        btncetak.setEnabled(false);
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });
        jPanel3.add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 90, 40));

        btntambah.setText("Bayar");
        btntambah.setEnabled(false);
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel3.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 90, 40));

        btnhapus.setBackground(new java.awt.Color(225, 0, 0));
        btnhapus.setText("Hapus");
        btnhapus.setEnabled(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel3.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 290, 90, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 340, 360));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Cicilan:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(99, 111, 254))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(99, 111, 254));
        jLabel14.setText("Merk:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(99, 111, 254));
        jLabel15.setText("Harga Total:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(99, 111, 254));
        jLabel16.setText("Kode Cicilan:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(99, 111, 254));
        jLabel17.setText("Kode Motor:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(99, 111, 254));
        jLabel18.setText("Nama Motor:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(99, 111, 254));
        jLabel19.setText("Cicilan Ke:");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(99, 111, 254));
        jLabel20.setText("Warna:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(99, 111, 254));
        jLabel21.setText("Kode Paket:");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lblhargatotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblhargatotal.setForeground(new java.awt.Color(99, 111, 254));
        lblhargatotal.setText("...");
        jPanel4.add(lblhargatotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(99, 111, 254));
        jLabel23.setText("Nilai Cicilan:");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(99, 111, 254));
        jLabel24.setText("Bunga:");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        lblkodepaket.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblkodepaket.setForeground(new java.awt.Color(99, 111, 254));
        lblkodepaket.setText("...");
        jPanel4.add(lblkodepaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        lblcicilanke.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblcicilanke.setForeground(new java.awt.Color(99, 111, 254));
        lblcicilanke.setText("...");
        jPanel4.add(lblcicilanke, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        lblkodecicilan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblkodecicilan.setForeground(new java.awt.Color(99, 111, 254));
        lblkodecicilan.setText("...");
        jPanel4.add(lblkodecicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        lblkodemotor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblkodemotor.setForeground(new java.awt.Color(99, 111, 254));
        lblkodemotor.setText("...");
        jPanel4.add(lblkodemotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        lblnamamotor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblnamamotor.setForeground(new java.awt.Color(99, 111, 254));
        lblnamamotor.setText("...");
        jPanel4.add(lblnamamotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        lblmerkmotor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblmerkmotor.setForeground(new java.awt.Color(99, 111, 254));
        lblmerkmotor.setText("...");
        jPanel4.add(lblmerkmotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        lblwarnamotor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblwarnamotor.setForeground(new java.awt.Color(99, 111, 254));
        lblwarnamotor.setText("...");
        jPanel4.add(lblwarnamotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(99, 111, 254));
        jLabel32.setText("Bulan");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        lbljmlcicilan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbljmlcicilan.setForeground(new java.awt.Color(99, 111, 254));
        lbljmlcicilan.setText("...");
        jPanel4.add(lbljmlcicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        lblnilaicicilan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblnilaicicilan.setForeground(new java.awt.Color(99, 111, 254));
        lblnilaicicilan.setText("...");
        jPanel4.add(lblnilaicicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        lblbunga.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblbunga.setForeground(new java.awt.Color(99, 111, 254));
        lblbunga.setText("...");
        jPanel4.add(lblbunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(99, 111, 254));
        jLabel22.setText("Uang Muka:");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        lbluangmuka.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbluangmuka.setForeground(new java.awt.Color(99, 111, 254));
        lbluangmuka.setText("...");
        jPanel4.add(lbluangmuka, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(99, 111, 254));
        jLabel36.setText("Jumlah Cicilan:");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 410, 310));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cari Data:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(99, 111, 254))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(99, 111, 254));
        jLabel33.setText("Berdasarkan:");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel5.add(txtcaridata, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 130, -1));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(99, 111, 254));
        jLabel34.setText("Cari Data:");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        cbberdasarkan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode", "Nama" }));
        jPanel5.add(cbberdasarkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 130, -1));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(99, 111, 254));
        jLabel35.setText("Kategori:");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 103, -1, -1));

        cbkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cicilan", "Data Beli" }));
        jPanel5.add(cbkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 130, -1));

        rSButtonMetro1.setText("Cari");
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, 270, 240));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tampilkan Data:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 112, 192))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbdatabeli.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbdatabeli);
        rbdatabeli.setText("Data Beli");
        rbdatabeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdatabeliActionPerformed(evt);
            }
        });
        jPanel6.add(rbdatabeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        rbdatacicilan.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbdatacicilan);
        rbdatacicilan.setSelected(true);
        rbdatacicilan.setText("Data Cicilan");
        rbdatacicilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdatacicilanActionPerformed(evt);
            }
        });
        jPanel6.add(rbdatacicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, 270, 55));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1183, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSPanelImage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSPanelImage1MouseClicked
        // TODO add your handling code here:
        dispose();
        new DashboardForm().setVisible(true);
    }//GEN-LAST:event_rSPanelImage1MouseClicked

    private void rbdatacicilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdatacicilanActionPerformed
        // TODO add your handling code here:
        cicilanController.showDataCicilan();
    }//GEN-LAST:event_rbdatacicilanActionPerformed

    private void rbdatabeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdatabeliActionPerformed
        // TODO add your handling code here:
        cicilanController.showBeliCredit();
    }//GEN-LAST:event_rbdatabeliActionPerformed

    private void tblcicilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcicilanMouseClicked
        // TODO add your handling code here:
        cicilanController.getValueAt();
    }//GEN-LAST:event_tblcicilanMouseClicked

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        // TODO add your handling code here:
        cicilanController.cariData();
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        cicilanController.bayarCicilan();
        cicilanController.showBeliCredit();
        cicilanController.clear();
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        cicilanController.hapusCicilan();
        cicilanController.showDataCicilan();
        cicilanController.clear();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        // TODO add your handling code here:
        cicilanController.cetakStruk();
        cicilanController.clear();
    }//GEN-LAST:event_btncetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BayarCicilanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BayarCicilanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BayarCicilanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BayarCicilanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BayarCicilanForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonMetro btncetak;
    private rojerusan.RSButtonMetro btnhapus;
    private rojerusan.RSButtonMetro btntambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbberdasarkan;
    private javax.swing.JComboBox<String> cbkategori;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblalamat;
    private javax.swing.JLabel lblbunga;
    private javax.swing.JLabel lblcicilanke;
    private javax.swing.JLabel lblhargatotal;
    private javax.swing.JLabel lbljeniskelamin;
    private javax.swing.JLabel lbljmlcicilan;
    private javax.swing.JLabel lblkodecicilan;
    private javax.swing.JLabel lblkodemotor;
    private javax.swing.JLabel lblkodepaket;
    private javax.swing.JLabel lblmerkmotor;
    private javax.swing.JLabel lblnama;
    private javax.swing.JLabel lblnamamotor;
    private javax.swing.JLabel lblnilaicicilan;
    private javax.swing.JLabel lblnoktp;
    private javax.swing.JLabel lblnotelp;
    private javax.swing.JLabel lbluangmuka;
    private javax.swing.JLabel lblwarnamotor;
    private rojerusan.RSButtonMetro rSButtonMetro1;
    private rojerusan.RSPanelImage rSPanelImage1;
    private javax.swing.JRadioButton rbdatabeli;
    private javax.swing.JRadioButton rbdatacicilan;
    private rojerusan.RSTableMetro tblcicilan;
    private javax.swing.JTextField txtcaridata;
    // End of variables declaration//GEN-END:variables
}
