/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Controller.BeliCashController;
import Model.BeliCash;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author LENOVO
 */
public class BeliCashForm extends javax.swing.JFrame {

    /**
     * Creates new form BeliCash
     */
    BeliCash beliCash;
    BeliCashController beliCashController;
    
    public BeliCashForm() {
        initComponents();
        setLocationRelativeTo(null);
        beliCashController=new BeliCashController(this);
        beliCashController.showDataBeli();
       
        
    }
    
    
    public JTextField getTxtCari()
    {
        return txtcari;
    }
    
    public JTextField getTxtNoKtp()
    {
        return txtnoktp;
    }
    
    public JTextField getTxtNamaPembeli()
    {
        return txtnamapembeli;
    }
    
    public JComboBox getCbJenisKelamin()
    {
        return cbjk;
    }
    
    public JComboBox getCbKategori()
    {
        return cbkategori;
    }
    
    public JComboBox getCbberdasarkan()
    {
        return cbberdasarkan;
    }
    
    public JTextField getTxtalamat()
    {
        return txtalamat;
    }
    
    public JTextField getTxtnoTelp()
    {
        return txtnotelp;
    }
    
    public JLabel getLblkodemotor()
    {
        return lblkodemotor;
    }
    
    public JLabel getLblnamamotor()
    {
        return lblnamamotor;
    }
    
    public JLabel getLblmerkmotor()
    {
        return lblmerkmotor;
    }
    
    public JLabel getLblwarnamotor()
    {
        return lblwarnamotor;
    }
    
    public JLabel getLblhargamotor()
    {
        return lblhargamotor;
    }
    
    public JLabel getLblStok()
    {
        return lblstok;
    }
   
    
    public JTable getTblBeliCash()
    {
        return tblbelicash;
    }
    
    public JRadioButton getRbDataBeli()
    {
        return rbpembelian;
    }
    
    public JRadioButton getRbDataMotor()
    {
        return rbmotor;
    }
    
    public ButtonGroup getbuttonGroup()
    {
        return buttonGroup1;
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnoktp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnamapembeli = new javax.swing.JTextField();
        cbjk = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnotelp = new javax.swing.JTextField();
        rSButtonMetro1 = new rojerusan.RSButtonMetro();
        rSButtonMetro2 = new rojerusan.RSButtonMetro();
        rSButtonMetro6 = new rojerusan.RSButtonMetro();
        rSButtonMetro5 = new rojerusan.RSButtonMetro();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblstok = new javax.swing.JLabel();
        lblkodemotor = new javax.swing.JLabel();
        lblnamamotor = new javax.swing.JLabel();
        lblmerkmotor = new javax.swing.JLabel();
        lblwarnamotor = new javax.swing.JLabel();
        lblhargamotor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbelicash = new rojerusan.RSTableMetro();
        jPanel5 = new javax.swing.JPanel();
        rbmotor = new javax.swing.JRadioButton();
        rbpembelian = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbberdasarkan = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cbkategori = new javax.swing.JComboBox<>();
        rSButtonMetro3 = new rojerusan.RSButtonMetro();
        rSButtonMetro4 = new rojerusan.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 111, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Image/back.png"))); // NOI18N
        rSPanelImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSPanelImage1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 680));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Biodata Pembeli:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(99, 111, 254))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(99, 111, 254));
        jLabel4.setText("Jenis Kelamin:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(99, 111, 254));
        jLabel5.setText("No KTP:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtnoktp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtnoktp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnoktpKeyTyped(evt);
            }
        });
        jPanel3.add(txtnoktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 160, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(99, 111, 254));
        jLabel6.setText("Nama:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, -1, -1));

        txtnamapembeli.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel3.add(txtnamapembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 160, 20));

        cbjk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan", "Lainnya" }));
        jPanel3.add(cbjk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 160, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(99, 111, 254));
        jLabel7.setText("Alamat:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtalamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel3.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 179, 160, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(99, 111, 254));
        jLabel8.setText("No Telp:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 223, -1, -1));

        txtnotelp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtnotelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnotelpKeyTyped(evt);
            }
        });
        jPanel3.add(txtnotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 160, 20));

        rSButtonMetro1.setBackground(new java.awt.Color(225, 0, 0));
        rSButtonMetro1.setText("Hapus");
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 265, 80, 30));

        rSButtonMetro2.setText("Tambah ");
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 265, 80, 30));

        rSButtonMetro6.setText("Clear");
        rSButtonMetro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro6ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 265, 80, 30));

        rSButtonMetro5.setText("Cetak Nota");
        rSButtonMetro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro5ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 265, 95, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 430, 320));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail Motor:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(99, 111, 254))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(99, 111, 254));
        jLabel9.setText("Kode Motor:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(99, 111, 254));
        jLabel10.setText("Nama Motor:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 78, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(99, 111, 254));
        jLabel11.setText("Merk Motor:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 106, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(99, 111, 254));
        jLabel12.setText("Warna Motor:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 134, -1, -1));

        lblstok.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblstok.setForeground(new java.awt.Color(99, 111, 254));
        lblstok.setText("...");
        jPanel4.add(lblstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 190, -1, -1));

        lblkodemotor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblkodemotor.setForeground(new java.awt.Color(99, 111, 254));
        lblkodemotor.setText("...");
        jPanel4.add(lblkodemotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 50, -1, -1));

        lblnamamotor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblnamamotor.setForeground(new java.awt.Color(99, 111, 254));
        lblnamamotor.setText("...");
        jPanel4.add(lblnamamotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 78, -1, -1));

        lblmerkmotor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblmerkmotor.setForeground(new java.awt.Color(99, 111, 254));
        lblmerkmotor.setText("...");
        jPanel4.add(lblmerkmotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 106, -1, -1));

        lblwarnamotor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblwarnamotor.setForeground(new java.awt.Color(99, 111, 254));
        lblwarnamotor.setText("...");
        jPanel4.add(lblwarnamotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 134, -1, -1));

        lblhargamotor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblhargamotor.setForeground(new java.awt.Color(99, 111, 254));
        lblhargamotor.setText("...");
        jPanel4.add(lblhargamotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 162, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(99, 111, 254));
        jLabel2.setText("Harga Motor:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 162, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(99, 111, 254));
        jLabel3.setText("Stok:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 320, 230));

        tblbelicash.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblbelicash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbelicashMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbelicash);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 1030, 200));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tampilkan Data:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(99, 111, 254))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbmotor.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbmotor);
        rbmotor.setText("Motor");
        rbmotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmotorActionPerformed(evt);
            }
        });
        jPanel5.add(rbmotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 23, -1, -1));

        rbpembelian.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbpembelian);
        rbpembelian.setSelected(true);
        rbpembelian.setText("Pembelian");
        rbpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbpembelianActionPerformed(evt);
            }
        });
        jPanel5.add(rbpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 23, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 320, 60));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cari Data:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(99, 111, 254))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(99, 111, 254));
        jLabel13.setText("Berdasarkan:");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 145, -1, -1));

        txtcari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel6.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 60, 150, 27));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(99, 111, 254));
        jLabel14.setText("Cari Data:");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 65, -1, -1));

        cbberdasarkan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode", "Nama" }));
        jPanel6.add(cbberdasarkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 145, 150, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(99, 111, 254));
        jLabel15.setText("Kategori:");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 105, -1, -1));

        cbkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pembeli", "Motor" }));
        jPanel6.add(cbkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 105, 150, -1));

        rSButtonMetro3.setText("Reset Tabel");
        rSButtonMetro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro3ActionPerformed(evt);
            }
        });
        jPanel6.add(rSButtonMetro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 230, 30));

        rSButtonMetro4.setText("Cari");
        rSButtonMetro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro4ActionPerformed(evt);
            }
        });
        jPanel6.add(rSButtonMetro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 230, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, 280, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSPanelImage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSPanelImage1MouseClicked
        // TODO add your handling code here:
        dispose();
        new DashboardForm().setVisible(true);
    }//GEN-LAST:event_rSPanelImage1MouseClicked

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        // TODO add your handling code here:
        beliCashController.deleteDataBeli();
        beliCashController.showDataBeli();
        beliCashController.clearMotor();
        beliCashController.clearPembeli();
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed
        // TODO add your handling code here:
       
        beliCashController.tambahDataBeli();
        beliCashController.clearMotor();
        beliCashController.clearPembeli();
    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void rbpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbpembelianActionPerformed
        // TODO add your handling code here:
        beliCashController.showDataBeli();
    }//GEN-LAST:event_rbpembelianActionPerformed

    private void rbmotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmotorActionPerformed
        // TODO add your handling code here:
        beliCashController.showMotor();
    }//GEN-LAST:event_rbmotorActionPerformed

    private void tblbelicashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbelicashMouseClicked
        // TODO add your handling code here:
                
        if(rbmotor.isSelected())
        {
             beliCashController.getRowDataMotor();
        }
        
        else if(rbpembelian.isSelected())
        {
            beliCashController.getRowDataBeli();
        }
       
    }//GEN-LAST:event_tblbelicashMouseClicked

    private void txtnotelpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnotelpKeyTyped
        // TODO add your handling code here:
        char stok = evt.getKeyChar();
        if (!(Character.isDigit(stok))) 
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtnotelpKeyTyped

    private void rSButtonMetro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro4ActionPerformed
        // TODO add your handling code here:
        beliCashController.cariData();
    }//GEN-LAST:event_rSButtonMetro4ActionPerformed

    private void rSButtonMetro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro3ActionPerformed
        // TODO add your handling code here:
        beliCashController.resetTable();
    }//GEN-LAST:event_rSButtonMetro3ActionPerformed

    private void rSButtonMetro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro6ActionPerformed
        // TODO add your handling code here:
        beliCashController.clearMotor();
        beliCashController.clearPembeli();
    }//GEN-LAST:event_rSButtonMetro6ActionPerformed

    private void txtnoktpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnoktpKeyTyped
        // TODO add your handling code here:
        char stok = evt.getKeyChar();
        if (!(Character.isDigit(stok))) 
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtnoktpKeyTyped

    private void rSButtonMetro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro5ActionPerformed
        // TODO add your handling code here:
        beliCashController.cetakNota();
    }//GEN-LAST:event_rSButtonMetro5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeliCashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeliCashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeliCashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeliCashForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeliCashForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbberdasarkan;
    private javax.swing.JComboBox<String> cbjk;
    private javax.swing.JComboBox<String> cbkategori;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblhargamotor;
    private javax.swing.JLabel lblkodemotor;
    private javax.swing.JLabel lblmerkmotor;
    private javax.swing.JLabel lblnamamotor;
    private javax.swing.JLabel lblstok;
    private javax.swing.JLabel lblwarnamotor;
    private rojerusan.RSButtonMetro rSButtonMetro1;
    private rojerusan.RSButtonMetro rSButtonMetro2;
    private rojerusan.RSButtonMetro rSButtonMetro3;
    private rojerusan.RSButtonMetro rSButtonMetro4;
    private rojerusan.RSButtonMetro rSButtonMetro5;
    private rojerusan.RSButtonMetro rSButtonMetro6;
    private rojerusan.RSPanelImage rSPanelImage1;
    private javax.swing.JRadioButton rbmotor;
    private javax.swing.JRadioButton rbpembelian;
    private rojerusan.RSTableMetro tblbelicash;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtnamapembeli;
    private javax.swing.JTextField txtnoktp;
    private javax.swing.JTextField txtnotelp;
    // End of variables declaration//GEN-END:variables
}
