/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Controller.MobilController;
import Model.Mobil;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author LENOVO
 */
public class DataMobilForm extends javax.swing.JFrame {

    /**
     * Creates new form DataMobilForm
     */
    int idMobil=0;
    
    Mobil mobil;
    MobilController mobilController;
    
    public DataMobilForm() {
        initComponents();
        setLocationRelativeTo(null);
        mobilController=new MobilController(this);
        mobilController.showDataMobil();
        lblkodemobil.setText(mobilController.autoNumber());
    }
    
    
    public JTextField getTxtCari()
    {
        return txtcari;
    }
    
    public JTable getTable()
    {
        return tblmobil;
    }
    
    public JLabel getLblKodeMobil()
    {
        return lblkodemobil;
    }
    
    
    public JTextField getTxtNamaMobil()
    {
        return txtnamamobil;
    }
    
    
    public JTextField getTxtMerkMobil()
    {
        return txtmerkmobil;
    }
    
    public JTextField getTxtWarnaMobil()
    {
        return txtwarnamobil;
    }
    
    public JTextField getTxtHargaMobil()
    {
        return txthargamobil;
    }
     
    public JTextField getTxtStockMobil()
    {
        return txtstokmobil;
    }
    
    
    public int getIdMobil()
    {
        return idMobil;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblkodemobil = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txthargamobil = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnamamobil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmerkmobil = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtstokmobil = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblmobil = new rojerusan.RSTableMetro();
        rSButtonMetro1 = new rojerusan.RSButtonMetro();
        rSButtonMetro2 = new rojerusan.RSButtonMetro();
        rSButtonMetro3 = new rojerusan.RSButtonMetro();
        rSButtonMetro4 = new rojerusan.RSButtonMetro();
        txtwarnamobil = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rSButtonMetro5 = new rojerusan.RSButtonMetro();
        jLabel9 = new javax.swing.JLabel();
        cbkategori = new javax.swing.JComboBox<>();
        rSButtonMetro6 = new rojerusan.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(99, 111, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Image/back.png"))); // NOI18N
        rSPanelImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSPanelImage1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 680));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(99, 111, 254));
        jLabel8.setText("Data Mobil");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(99, 111, 254));
        jLabel1.setText("Harga Mobil:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, -1, -1));

        lblkodemobil.setText("...");
        jPanel1.add(lblkodemobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 185, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(99, 111, 254));
        jLabel2.setText("Kategori:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 75, -1, -1));

        txthargamobil.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txthargamobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txthargamobilMouseClicked(evt);
            }
        });
        txthargamobil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthargamobilKeyTyped(evt);
            }
        });
        jPanel1.add(txthargamobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 210, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(99, 111, 254));
        jLabel3.setText("Stok Mobil:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        txtnamamobil.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtnamamobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 200, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(99, 111, 254));
        jLabel4.setText("Kode Mobil:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        txtmerkmobil.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtmerkmobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 200, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(99, 111, 254));
        jLabel5.setText("Nama Mobil:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        txtcari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 35, 140, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(99, 111, 254));
        jLabel6.setText("Merk Mobil:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        txtstokmobil.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtstokmobil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtstokmobilKeyTyped(evt);
            }
        });
        jPanel1.add(txtstokmobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 210, 30));

        tblmobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblmobil.setCellSelectionEnabled(true);
        tblmobil.setColorBackgoundHead(new java.awt.Color(99, 111, 254));
        tblmobil.setGridColor(new java.awt.Color(255, 255, 255));
        tblmobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmobilMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblmobil);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 710, 220));

        rSButtonMetro1.setBackground(new java.awt.Color(99, 111, 254));
        rSButtonMetro1.setText("Clear");
        rSButtonMetro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 100, 30));

        rSButtonMetro2.setBackground(new java.awt.Color(99, 111, 254));
        rSButtonMetro2.setText("Tambah");
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 100, 30));

        rSButtonMetro3.setBackground(new java.awt.Color(99, 111, 254));
        rSButtonMetro3.setText("Edit");
        rSButtonMetro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 100, 30));

        rSButtonMetro4.setBackground(new java.awt.Color(225, 0, 0));
        rSButtonMetro4.setText("Hapus");
        rSButtonMetro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro4ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 100, 30));

        txtwarnamobil.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtwarnamobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 210, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(99, 111, 254));
        jLabel7.setText("Warna Mobil:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        rSButtonMetro5.setBackground(new java.awt.Color(99, 111, 254));
        rSButtonMetro5.setText("Cari");
        rSButtonMetro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro5ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 70, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(99, 111, 254));
        jLabel9.setText("Cari:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 35, -1, -1));

        cbkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama", "Merk" }));
        jPanel1.add(cbkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 75, 140, -1));

        rSButtonMetro6.setBackground(new java.awt.Color(99, 111, 254));
        rSButtonMetro6.setText("Isi tabel");
        rSButtonMetro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro6ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMetro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 75, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSPanelImage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSPanelImage1MouseClicked
        // TODO add your handling code here:
        dispose();
        new DashboardForm().setVisible(true);
    }//GEN-LAST:event_rSPanelImage1MouseClicked

    private void rSButtonMetro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_rSButtonMetro1ActionPerformed

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed
        // TODO add your handling code here:
        
        if(mobilController.validasi())
        {
            JOptionPane.showMessageDialog(null, "Silahkan isi Kolom Yang Kosong");
        }
        
        else
        {
            mobilController.tambahMobil();
            mobilController.clear();
            mobilController.showDataMobil();
            mobilController.autoNumber();
        }
        
    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void rSButtonMetro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro3ActionPerformed
        // TODO add your handling code here:
        if(mobilController.validasi())
        {
            JOptionPane.showMessageDialog(null, "Silahkan isi kolom yang kosong");
        }
        
        else if(mobilController.getId().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang mau diedit");
        }
        
        else
        {
            mobilController.updateMobil();
            mobilController.clear();
            mobilController.autoNumber();
            mobilController.showDataMobil();
        }
    }//GEN-LAST:event_rSButtonMetro3ActionPerformed

    private void rSButtonMetro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro4ActionPerformed
        // TODO add your handling code here:
        String id=mobilController.getId();
        
        if(id.equals(""))
        {
           JOptionPane.showMessageDialog(null,"Silahkan pilih data yang mau dihapus");
        }
        
        else
        {
            mobilController.deleteMobil();
            mobilController.clear();
            mobilController.autoNumber();
            mobilController.showDataMobil();
        }
    }//GEN-LAST:event_rSButtonMetro4ActionPerformed

    private void txtstokmobilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstokmobilKeyTyped
        // TODO add your handling code here:
        char stok = evt.getKeyChar();
        if (!(Character.isDigit(stok))) 
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtstokmobilKeyTyped

    private void txthargamobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txthargamobilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargamobilMouseClicked

    private void txthargamobilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargamobilKeyTyped
        // TODO add your handling code here:
        char stok = evt.getKeyChar();
        if (!(Character.isDigit(stok))) 
        {
            evt.consume();
        }
    }//GEN-LAST:event_txthargamobilKeyTyped

    private void tblmobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmobilMouseClicked
        // TODO add your handling code here:
        mobilController=new MobilController(this);
        mobilController.getRowData();
    }//GEN-LAST:event_tblmobilMouseClicked

    private void rSButtonMetro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro5ActionPerformed
        // TODO add your handling code here:
        int index=cbkategori.getSelectedIndex();
        
        if(index==0)
        {
            mobilController.cariNamaMobil();
        }
        
        else if(index==1)
        {
            mobilController.cariMerkMobil();
        }
    }//GEN-LAST:event_rSButtonMetro5ActionPerformed

    private void rSButtonMetro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro6ActionPerformed
        // TODO add your handling code here:
        mobilController.showDataMobil();
    }//GEN-LAST:event_rSButtonMetro6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataMobilForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataMobilForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataMobilForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataMobilForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataMobilForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbkategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblkodemobil;
    private rojerusan.RSButtonMetro rSButtonMetro1;
    private rojerusan.RSButtonMetro rSButtonMetro2;
    private rojerusan.RSButtonMetro rSButtonMetro3;
    private rojerusan.RSButtonMetro rSButtonMetro4;
    private rojerusan.RSButtonMetro rSButtonMetro5;
    private rojerusan.RSButtonMetro rSButtonMetro6;
    private rojerusan.RSPanelImage rSPanelImage1;
    private rojerusan.RSTableMetro tblmobil;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txthargamobil;
    private javax.swing.JTextField txtmerkmobil;
    private javax.swing.JTextField txtnamamobil;
    private javax.swing.JTextField txtstokmobil;
    private javax.swing.JTextField txtwarnamobil;
    // End of variables declaration//GEN-END:variables
}
